name: Build wheels

on:
  workflow_dispatch:
    inputs:
      build_type:
        type: choice
        required: true
        description: 'Build Type (ignored if using artifacts from prior run)'
        default: 'Release'
        options:
        - 'Release'
        - 'Debug'
      version:
        type: string
        description: Version number to create wheels with (e.g. 0.2.0). Defaults to 0.0.0 if unspecified
        required: false
      cudaq_wheels:
        type: choice
        required: true
        description: 'CUDA-Q wheel source (released version from PyPI or Custom built using .cudaq_version in repo)'
        default: 'Custom'
        options:
        - 'Custom'
        - 'PyPI'
      assets_repo:
        type: string
        description: Retrieve assets from a draft release from this repo (e.g. NVIDIA/cudaqx)
        required: false
      assets_tag:
        type: string
        description: Retrieve assets from a draft release with this tag (e.g. installed_files-1)
        required: false
      artifacts_from_run:
        type: string
        description: Optional argument to take artifacts from a prior run of this workflow; facilitates rerunning a failed workflow without re-building the artifacts.
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-cudaqx-wheels:
    name: Build CUDA-QX wheels
    if: ${{ !inputs.artifacts_from_run }}
    runs-on: linux-${{ matrix.platform }}-cpu8
    # CUDAQ requires a highly specialized environment to build. Thus, it is much
    # easier to rely on their's devdeps images to do the building.
    # FIXME: there is no guarantee that this CUDA-Q image aligns with the CUDA-Q
    # commit that we are trying to align with.
    container: ghcr.io/nvidia/cuda-quantum-devdeps:manylinux-${{ matrix.platform }}-${{ matrix.toolchain.id }}-main
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        python: ['3.10', '3.11', '3.12']
        platform: ['amd64', 'arm64']
        toolchain:
          - id: cu12.0-gcc11
            cc: gcc-11
            cxx: g++-11
            build-type: Release

    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      # Do this early to help validate user inputs (if present)
      - name: Fetch assets
        env:
          GH_TOKEN: ${{ github.token }}
        id: fetch-assets
        run: |
          bash .github/workflows/scripts/install_git_cli.sh
          if [[ -n "${{ inputs.assets_repo }}" ]] && [[ -n "${{ inputs.assets_tag }}" ]]; then
            # Fetch the assets into this directory
            gh release download -R ${{ inputs.assets_repo }} ${{ inputs.assets_tag }}
            ls
          fi

      - name: Get required CUDAQ version
        id: get-cudaq-version
        uses: ./.github/actions/get-cudaq-version

      - name: Get CUDAQ code
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.get-cudaq-version.outputs.repo }}
          ref: ${{ steps.get-cudaq-version.outputs.ref }}
          path: cudaq
          set-safe-directory: true

      - name: Build CUDAQ toolchain
        run: |
          .github/workflows/scripts/build_cudaq.sh --python-version ${{ matrix.python }}

      - name: Build CUDA-QX wheels
        env:
          SUFFIX: ${{ matrix.platform == 'amd64' && 'x86_64' || 'aarch64' }}
        run: |
          if [[ -n "${{ inputs.assets_repo }}" ]] && [[ -n "${{ inputs.assets_tag }}" ]]; then
            # Extract the decoder that needs to be embedded in the wheel
            mkdir -p tmp
            PYVER=$(echo ${{ matrix.python }} | tr -d '.')
            unzip -d tmp cudaq_qec-*-cp${PYVER}-cp${PYVER}-manylinux*${SUFFIX}*.whl
            export QEC_EXTERNAL_DECODERS=$(pwd)/tmp/cudaq_qec/lib/decoder-plugins/libcudaq-qec-nv-qldpc-decoder.so
          fi
          .github/workflows/scripts/build_wheels.sh \
              --cudaq-prefix /usr/local/cudaq \
              --build-type ${{ inputs.build_type }} \
              --python-version ${{ matrix.python }} \
              --version ${{ inputs.version || '0.0.0' }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-py${{ matrix.python }}-${{ matrix.platform }}
          path: /wheels/**
          retention-days: 14

  # Building the CUDA-Q wheels must be done outside of a container context, so
  # this is a separate job.
  build-cudaq-wheels:
    name: Build CUDA-Q wheels
    if: ${{ !inputs.artifacts_from_run && inputs.cudaq_wheels == 'Custom'}}
    strategy:
      fail-fast: false
      matrix:
        platform: ['amd64', 'arm64']
    # Use 32 CPUs rather than 8 (above) because we are only spawning one job per
    # platform rather than one job per Python version per platform.
    runs-on: ${{ startsWith(github.repository, 'NVIDIA/cudaqx') && format('linux-{0}-cpu32', matrix.platform) || 'ubuntu-latest' }}
    permissions:
      actions: write
      contents: read
      pull-requests: read
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      - name: Get required CUDAQ version
        id: get-cudaq-version
        uses: ./.github/actions/get-cudaq-version

      - name: Get CUDAQ wheels
        uses: ./.github/actions/get-cudaq-wheels
        with:
          repo: ${{ steps.get-cudaq-version.outputs.repo }}
          ref: ${{ steps.get-cudaq-version.outputs.ref }}
          token: ${{ secrets.CUDAQ_ACCESS_TOKEN }}
          save-build: true
          platform: ${{ matrix.platform }}

      - name: Upload CUDAQ wheels
        uses: actions/upload-artifact@v4
        with:
          name: cudaq-wheels-${{ matrix.platform }}
          path: /cudaq-wheels
          retention-days: 14
          if-no-files-found: error

  test-cudaqx-wheels:
    name: Test CUDA-QX wheels (CPU)
    needs: [build-cudaqx-wheels, build-cudaq-wheels]
    if: ${{ !failure() && !cancelled() }}
    runs-on: linux-${{ matrix.platform }}-cpu4
    container: ubuntu:22.04
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python: ['3.10', '3.11', '3.12']
        platform: ['amd64', 'arm64']
  
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          set-safe-directory: true
  
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
  
      - name: Install requirements
        run: |
          bash .github/workflows/scripts/install_git_cli.sh
          apt install -y --no-install-recommends libgfortran5 unzip
  
      - name: Download CUDA-Q wheels
        if: ${{ inputs.cudaq_wheels == 'Custom' }}
        uses: actions/download-artifact@v4
        with:
          name: cudaq-wheels-${{ matrix.platform }}
          path: /cudaq-wheels
          run-id: ${{ inputs.artifacts_from_run || github.run_id }}
          github-token: ${{ inputs.artifacts_from_run && secrets.WORKFLOW_TOKEN || github.token }}

      - name: Download CUDA-QX wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-py${{ matrix.python }}-${{ matrix.platform }}
          path: /wheels
          run-id: ${{ inputs.artifacts_from_run || github.run_id }}
          github-token: ${{ inputs.artifacts_from_run && secrets.WORKFLOW_TOKEN || github.token }}
  
      - name: Test wheels
        run: |
          ls /wheels
          bash scripts/ci/test_wheels.sh ${{ matrix.python }}
  
  test-wheels-gpu:
    name: Test CUDA-QX wheels (GPU)
    needs: [build-cudaqx-wheels, build-cudaq-wheels]
    if: ${{ !failure() && !cancelled() }}
    runs-on: linux-${{ matrix.runner.arch }}-gpu-${{ matrix.runner.gpu }}-latest-1
    container:
      image: nvidia/cuda:12.0.0-base-ubuntu22.04
      # Enable this if you want to collect core files. (You may might to enable
      # Debug builds if you're doing this.)
      #options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        runner: [
          { arch: arm64, gpu: a100 },
          { arch: amd64, gpu: v100 },
        ]
        python: ['3.10', '3.11', '3.12']
  
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          set-safe-directory: true
  
      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
  
      - name: Install requirements
        run: |
          bash .github/workflows/scripts/install_git_cli.sh
          apt install -y --no-install-recommends libgfortran5 unzip
          #echo 'core.%p' | tee /proc/sys/kernel/core_pattern
          #echo "Running cat /proc/sys/kernel/core_pattern"
          #cat /proc/sys/kernel/core_pattern
  
      - name: Download CUDA-Q wheels
        if: ${{ inputs.cudaq_wheels == 'Custom' }}
        uses: actions/download-artifact@v4
        with:
          name: cudaq-wheels-${{ matrix.runner.arch }}
          path: /cudaq-wheels
          run-id: ${{ inputs.artifacts_from_run || github.run_id }}
          github-token: ${{ inputs.artifacts_from_run && secrets.WORKFLOW_TOKEN || github.token }}

      - name: Download CUDA-QX wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-py${{ matrix.python }}-${{ matrix.runner.arch }}
          path: /wheels
          run-id: ${{ inputs.artifacts_from_run || github.run_id }}
          github-token: ${{ inputs.artifacts_from_run && secrets.WORKFLOW_TOKEN || github.token }}
  
      - name: Test wheels
        run: |
          ls /wheels
          bash scripts/ci/test_wheels.sh ${{ matrix.python }}

      # - name: Upload any core files
      #   if: success() || failure()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: core-files-${{ matrix.python }}-arm64
      #     path: core.*
